services:
  - type: web
    name: mcrypto-bot
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "8000"
  # Redis Service (Moved from databases)
  - type: redis
    name: mcrypto-redis

databases:
  - name: mcrypto-db
    databaseName: mcrypto
    user: mcrypto_user
    plan: free
